version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/npm)"
  - package-ecosystem: npm
    directory: examples/fa2
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/npm)"
  - package-ecosystem: npm
    directory: examples/hello-world
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/npm)"
  - package-ecosystem: npm
    directory: packages/jsmv-types
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/npm)"
  - package-ecosystem: npm
    directory: packages/jsmv
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/npm)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/actions)"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_cli
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_core
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_crypto
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_proto
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_kernel
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_node
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_api
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
  - package-ecosystem: cargo
    directory: crates/jsmv_wpt
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/cargo)"
